# references:
language: objective-c
osx_image: xcode8.3
branches:
  only: 
    - master  
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

  matrix:
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="SwiftyBase" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  
script:

  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "Example/SwiftyBase.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "Example/SwiftyBase.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "Example/SwiftyBase.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "Example/SwiftyBase.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "Example/SwiftyBase.xcworkspace" -scheme "SwiftyBase-Example" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
   - bash <(curl -s https://codecov.io/bash)
   - sleep 5 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725    
